### ISSUE TITLE
Linksharing node count and piece count mismatch

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-mt#104]
It was observed that when a single segment object was uploaded and shared via Linksharing, the node count shown on the shared page was different to the number of pieces. In this case, we expect the numbers in the screenshot below should be the same, and a node can't have more than one piece.

![nodecount](https://user-images.githubusercontent.com/138450/140856947-b2dca503-dbf3-4d6b-b020-620d0185cc9c.png)

It's believed this is due to the count only being for nodes that are online, so if some are offline then it would report a lower number.

Since counting nodes may not be reliable, the message could be made more more generic. Perhaps some design thought is needed here.

**Comment by wthorp** [comment]
Likely duplicates as #63

**Comment by wthorp** [comment]
Dupe
