### ISSUE TITLE
Add MVP linksharing support for zip files

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#106]
We'd like to support returning a single file from a ZIP file.  https://github.com/jtolio/zipper/ might be a good starting point.  We just want to be able to reference and return a single file from within a zip archive.  Make sure we're minimizing backend calls without implementing any type of caching or fancy optimizations.

**Comment by wthorp** [comment]
JT has pointed out that zipper may be added to uplinkng https://review.dev.storj.io/c/storj/storj/+/6107

**Comment by wthorp** [comment]
Also, while Zip files are interesting, it might be nice to make this a more flexible solution.
"karl suggested https://github.com/vasi/pixz"
"chromium has a pak file format that looks poorly documented but might do exactly what we need"

**Comment by amwolff** [comment]
Closed by 593d92fbc162d457e7b9874bc49f20a80c832a97.
