### ISSUE TITLE
Credentials which are restricted to bucket do not work for Gateway

### ISSUE THREAD

**Issue by Erikvv** [storj/gateway-mt#129]
If I generate credentials with a bucket restriction like so

```
uplink share sj://orbiter --readonly=false --not-after +24h --register
```

```
Sharing access to satellite 12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs@europe-west-1.tardigrade.io:7777
=========== ACCESS RESTRICTIONS ==========================================================
Download  : Allowed
Upload    : Allowed
Lists     : Allowed
Deletes   : Allowed
NotBefore : No restriction
NotAfter  : 2022-01-12 14:10:41
Paths     : sj://orbiter/ (entire bucket)
```

These credentials don't work for the S3 Gateway-MT, PUT and GET give a 403.
Linksharing works fine though (with --public).

**Comment by wthorp** [comment]
I failed to recreate this locally with storj-sim on Jan 11 2022, using the command `uplink share sj://test/ --access  $(storj-sim network env GATEWAY_0_ACCESS) --auth-service http://localhost:8000 --base-url=http://localhost:8080 --readonly=false --not-after=+24h --register`.

**Comment by Erikvv** [comment]
I am not able to reproduce the issue any more. It must have been transient.

Speculation: some kind of replication sync issue with the auth service database? And then gateway-mt's authclient cache is polluted so it doesn't clear?

If you see no reason to investigate further we can close it. I do have the impression like we get a somewhat disproportionate number of customers who have issues getting it set up, @dominickmarino can maybe attest.

**Comment by Erikvv** [comment]
I have tested like a dozen insane theories and have a finding: if you restrict an Access Grant with a bucket restriction and then restrict it again without a bucket restriction it is broken. uplink-cli does not even show the bucket restriction any more.

So this is not related to edge services, need to create a new bug

**Comment by Erikvv** [comment]
https://github.com/storj/uplink/issues/76
