### ISSUE TITLE
Get Splunk tests working on CI

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#132]
Make this a regular part of our build process

**Comment by halkyon** [comment]
Quick attempt building and running directly from the branch shows that it's working: https://review.dev.storj.io/c/storj/gateway-mt/+/6672. We will want to get the repo hooked up to Gerrit and have the [branch containing the necessary changes](https://github.com/storj/s3-tests/tree/test-changes) reviewed, then get the image building in Jenkins.
