### ISSUE TITLE
S3-tests expected error code verification

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#133]
In the S3 tests we've noticed that some of our error codes are different than they expect, EG 400 instead of 403.  Work to understand why we're different, cross reference against S3, and produce either fixes or a documentation.  Split this ticket into different parts if necessary.  https://github.com/storj/s3-tests

**Comment by halkyon** [comment]
Apart from major features like ACL and versioning, here's a complete list of issues for which tests are currently skipped:

New issues raised:

* Empty or invalid Authorization header returns different response: https://github.com/storj/gateway-mt/issues/142
* Invalid Content-MD5 header returns incorrect error code: https://github.com/storj/gateway-mt/issues/140
* Dot delimiter not allowed: https://github.com/storj/gateway-mt/issues/143

Existing issues: 

* No lexicographic ordering: https://github.com/storj/gateway-st/issues/49
* Custom metadata not saved for multi-part upload: https://github.com/storj/gateway-mt/issues/39
* Minimum part size error not mapped: https://github.com/storj/gateway-mt/issues/105
* Part validation disabled: https://github.com/storj/gateway-mt/issues/43

These are annotated in https://github.com/storj/splunk-s3-tests/blob/main/s3tests/functional/test_s3.py and https://github.com/storj/splunk-s3-tests/blob/main/s3tests/functional/test_headers.py

FYI @wthorp
