### ISSUE TITLE
Design zero-downtime migration from CockroachDB to the new auth database

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#144]
The new auth database [blueprint](https://review.dev.storj.io/c/storj/gateway-mt/+/6030) contains the Design/Migration section about migrating from the current CockroachDB to the new solution. I think it might be a good idea to discuss this in detail. For example:

1. where to put new code;
2. what exactly the production-owner engineer would do to migrate;
3. analyze some scenarios that could result in downtime and how to mitigate them in such cases.

This issue might be a good place to discuss the solution as everyone can chime in.

**Comment by wthorp** [comment]
direct blueprint link: https://github.com/storj/gateway-mt/blob/main/docs/blueprints/new-auth-database.md

**Comment by egonelbre** [comment]
Based on the rough assumption that the database is mostly immutable, we can
use the following strategy for zero-downtime migration:

* We use the new database as the primary source.
* When the new database does not contain the information:
   * We'll check if it exists in the old database.
   * If it exists, we'll migrate.

In the background we'll migrate each row to the new database, taking into
account that some of the data might have been moved or deleted.

During the migration the deletion should be use tombstones, (i.e. set an
expires date). This allows to ensure we don't reintroduce deleted data during
migration.

When the migration has completed. Then we can turn-off checks against the
old database and delete the tombstoned things as needed.

Note about deletes and invalidate. In those cases we can first:

1. migrate the existing value without modification
2. delete or invalidate it in the new database

**Comment by halkyon** [comment]
In the distributed scenario, do you see migration as picking one of the nodes to do the background migration, and individual nodes will migrate on-demand as requests come in?

**Comment by egonelbre** [comment]
@halkyon since the database is eventually consistent with a clear state machine, the order how things are migrated shouldn't matter.

We can imagine the state diagram of an record roughly as:

``` mermaid
flowchart LR
missing --> exists --> invalidated --> deleted
```

This means that as long as we iterate over-all data and ensure the "max" state across all of the data, then we can ensure that we have migrated all the data.

When the migration content is put into place, then the "max" diagram will look like:

``` mermaid
flowchart LR
missing --> exists --> invalidated --> deleted
missingnew[missing new] --> existsnew[exists new] --> invalidatednew[invalidated new] --> deletednew[deleted new]
exists -- migrate --> existsnew
invalidated -- migrate --> invalidatednew
deleted -- migrate --> deletednew
```

That being said, my rough idea is that all nodes migrate on-demand during normal operation. This ensures that frequently used accesses can be reached fast. And the rest of data is migrated in the background.

**Comment by egonelbre** [comment]
Marking as design finished for now, since this seems a sufficient detail for implementation. We can clarify different aspects once we discover more problems.

**Comment by wthorp** [comment]
Some small TBDs from standup:  its seems most convenient, although not critical, to have a separate process run the migration.  Artur believes that we can connect to Badger from more than one process, that would need to be verified.  If not, we could potentially re-use new synchronization frameworks and have a new, stand-alone migration "node" which synchronizes records from the CRDB to the updated BadgerDB Auth Service nodes.

**Comment by amwolff** [comment]
I re-read the documentation, and it won't be possible to open the same database from another process, unfortunately.

> Please note that Badger obtains a lock on the directories so multiple processes cannot open the same database at the same time.

https://dgraph.io/docs/badger/get-started/#opening-a-database

Maybe there's some way to open it if reading only? But in our case, this won't help, so we'll need to start the migration from the authservice node itself.

**Comment by amwolff** [comment]
> [...] If not, we could potentially re-use new synchronization frameworks and have a new, stand-alone migration "node" which synchronizes records from the CRDB to the updated BadgerDB Auth Service nodes.

I really like this idea. This seems like a satisfactory solution to me.
