### ISSUE TITLE
multi-part uploads with same bucket and key are overwritten

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-mt#149]
If creating a multi-part upload with same bucket and key twice or more, the existing upload is overwritten, which differs from AWS S3 behaviour.

Storj gateways:

```
aws s3api create-multipart-upload --bucket test-files --key test-file-mpu
aws s3api create-multipart-upload --bucket test-files --key test-file-mpu
aws s3api list-multipart-uploads --bucket test-files
[1 result]
```

AWS S3:

```
aws s3api create-multipart-upload --bucket test-files --key test-file-mpu
aws s3api create-multipart-upload --bucket test-files --key test-file-mpu
aws s3api list-multipart-uploads --bucket test-files
[2 results]
```

This was discovered in s3 tests: https://github.com/storj/splunk-s3-tests/blob/main/s3tests/functional/test_s3.py#L6922

This might be part of a much larger piece of work around versioning, for which there's a roadmap item here: https://github.com/storj/roadmap/issues/23. In that case, the immediate thing we could do is document the compatibility differences as part of https://github.com/storj/gateway-mt/issues/136

**Comment by mniewrzal** [comment]
This should be fixed now. We can enable splunk testsuite test.
