### ISSUE TITLE
missing content-length header produces different error response to S3

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-mt#150]
One of the [s3-tests produces a failure](https://github.com/storj/splunk-s3-tests/blob/main/s3tests/functional/test_headers.py#L346). The test expected 411 Length Required when Content-Length header was omitted from the request, but got a 400 Bad Request.

After looking at the code, minio `PutObjectHandler` checks `r.ContentLength` from `http.Request` to determine if it should return a 411 Length Required response, but this is determined by the content body as the request is read, even if the `Content-Length` header is missing from the request. It is set as `-1` if the request was HTTP/2, according to the code in `readRequest` in the go http package, but not for HTTP/1.1. In the failing test, it was observed `r.ContentLength` was `0` with the missing header.

The same test against AWS S3 passes, which implies `Content-Length` header must be given for PutObject requests.

A suggested fix is to check Content-Length header exists in the request headers, or change the size check to `<= 0`. I'm not entirely sure of the implications of the latter change though.

**Comment by wthorp** [comment]
The S3 docs are interesting:  https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html only says `This parameter is useful when the size of the body cannot be determined automatically.`  What's weird though is that it looks like we should return 411 because there's a check for it: https://github.com/minio/minio/blob/84b121bbe141d1c250cd22c075b9eb4fc9abd4cc/cmd/object-handlers.go#L1592

**Comment by halkyon** [comment]
> What's weird though is that it looks like we should return 411 because there's a check for it: [https://github.com/minio/minio](https://github.com/minio/minio/blob/84b121bbe141d1c250cd22c075b9eb4fc9abd4cc/cmd/object-handlers.go#L1592)

Yeah. Go is determining the body is zero length instead, and therefore not validating correctly by the minio rules, but it gets more complicated due to HTTP/2 and 1.1 seemingly, after taking a look at the net/http code. There's not much in the way of comments around the size check in minio, as other endpoints check `size <= 0`, but PutObjectHandler only checks `size = -1`. :shrug: Regardless, black box testing S3 indicates that the Content-Type header is needed even if their docs make it seem like it could be optional.

**Comment by wthorp** [comment]
I'm not sure how happy I am with this, but: https://review.dev.storj.io/c/storj/gateway-mt/+/6837

**Comment by wthorp** [comment]
https://review.dev.storj.io/c/storj/gateway/+/6883 bumps Minio in Gateway-ST to include this
