### ISSUE TITLE
Why did the compilation fail and where is the storj-release command

### ISSUE THREAD

**Issue by muyan9** [storj/gateway-mt#19]
[root@localhost gateway-mt]# make binaries
for C in gateway-mt authservice linksharing; do\
	make binary COMPONENT=$C || exit $? \
; done
make[1]: Entering directory '/opt/gateway-mt'
# freebsd/amd64 target is currently skipped until https://storjlabs.atlassian.net/browse/GMT-302
storj-release --components="cmd/gateway-mt" --go-version="1.15.14" --branch="" --skip-osarches="freebsd/amd64"
/bin/sh: storj-release: command not found
make[1]: *** [Makefile:112: binary] Error 127
make[1]: Leaving directory '/opt/gateway-mt'
make: *** [Makefile:117: binaries] Error 2

**Comment by Erikvv** [comment]
This seems a private command on the Jenkins server.

You can build the binaries using for example `go build cmd/gateway-mt/main.go`. Does that help you?

**Comment by amwolff** [comment]
Hi @muyan9,

`storj-release` is available [here](https://github.com/storj/ci/tree/main/storj-release) if you would like to use it to build components.

As Erik points out, you can always build or install Gateway-MT/Auth Service/Link Sharing Service without it, e.g.

```
% cd gateway-mt/cmd/gateway-mt/
% go build
```

**Comment by muyan9** [comment]
@Erikvv @amwolff Thanks for the help, I know go build can compile.
The gateway command compiled by make install-sim has no setup option. I want to see why.
Maybe I have confused the use of gateway-mt and gateway-st. I will study the documentation later.

**Comment by Erikvv** [comment]
Indeed gateway-mt does not have a setup command.

In order to get S3 credentials you need to run it together with https://github.com/storj/gateway-mt/blob/main/cmd/authservice/main.go and do it via the REST api:

```
curl --request POST \
  --url https://auth.ap1.storjshare.io/v1/access \
  --header 'Content-Type: application/json' \
  --data '{
	"access_grant": "asdf",
	"public": false
}'
```

We do intend to converge gateway-mt and gateway-st in the future.

**Comment by muyan9** [comment]
@Erikvv oh， thank you
