### ISSUE TITLE
badgerauth: observability

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#200]
### Goal
Determine what/how we should be "observing" for the new badgerauth implementation. What types of logging and or alerts are needed?

### Acceptance Criteria
- Logging/alerts defined (probably dependent on metrics defined in https://github.com/storj/gateway-mt/issues/199)

**Comment by NiaStorj** [comment]
according to @amwolff this ticket is no longer needed. So I will be closing this ticket.
