### ISSUE TITLE
[New Auth Database] Create Chronograf Dashboard

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#205]
## Goal

Create a Chronograf dashboard with badgerauth's metrics.

## Acceptance Criteria

- The dashboard is created with predefined metrics.
- Link added to this ticket, with a list/description of each metric

**Comment by ferristocrat** [comment]
@amwolff - added the second bullet point to the acceptance criteria... let me know if you don't think that's right

**Comment by halkyon** [comment]
https://chronograf.datasci.storj.io/sources/3/dashboards/128

Rate metrics (for both badgerauth and sqlauth):
* Database put rate
* Database get rate

Time metrics (90% percentile average across instances, for both badgerauth and sqlauth):
* Database put time (r90)
* Database get time (r90)

Error metrics:
* Database put error
* Database get error

Peer metrics (for checking connectivity between authdb nodes):
* Peer down rate
* Peer dial time (r90)
* Peer peek rate (for when broadcast gets are being made to other peers where a key isn't found)

Database/internal stuff:
* Database expiring/non-expiring insert rate (useful mostly for seeing if people are inserting a lot of non-expiring access keys)
* Badger GC time
* Current clock (also useful for the migration)

Migration specific:
* Migration hit/miss rate

We used this during deployment of the new database and it seemed quite helpful.

If you can think of anything we're missing, let me know. This dashboard is ongoing work.

sqlauth and migration graphs will be removed once we no longer have the fallback to the old database.
