### ISSUE TITLE
Publicly accessable record of storage, but not content

### ISSUE THREAD

**Issue by YurkoWasHere** [storj/gateway-mt#209]
It would be helpful if there was a way to indicate publicly with a link the record/proof of an asset being stored on storj, but not allow access to the asset itself.

One idea could be to use link sharing to display the the file existence, name, size, and object map if the access grant has listing permission, but no read permission.

**Comment by YurkoWasHere** [comment]
At starling lab we deal with data that may be sensitive for whatever reason, and cannot be shared publicly. However the existence of this data is not sensitive and in fact we register its existence in public spaces such as blockchains. Proof it exists/still exists on Storj would be a valuable public piece deceleration.

An example could be with Filecoin. We use the deal transaction on chain to proves that the file exists and that it will continue to exist for a period of time.
https://filfox.info/en/message/bafy2bzacedpv5fyjetg4zkqohxzfy53qxrl3um7gxdbcwtdsxfrahznpmu2v2

During some brain storming one idea was to look at using `--disallow-reads` but this yielded an access denied. 

For our presentation at consensus we use a screen shot but long term it would be nice to be able to publicly link to evidence that the content exists and can be accessible under the right conditions.

**Comment by amwolff** [comment]
Thank you for a thorough explanation, @YurkoWasHere. I will pass this to our PM (cc @ferristocrat).

**Comment by kaloyan-raev** [comment]
https://review.dev.storj.io/c/storj/storj/+/8790 addresses the required change on the satellite.

**Comment by kaloyan-raev** [comment]
https://review.dev.storj.io/c/storj/gateway-mt/+/8869 improves the error handling on the linksharing side when a download is attempted with a list-only access grant.

**Comment by kaloyan-raev** [comment]
The changes are now deployed on all satellites and edge instances.

@YurkoWasHere This feature is now available for you. You can use `--disallow-reads` to generate list-only access grants. The linksharing service will display the file's metadata, but won't allow downloading it.

Here is an example:
https://link.storjshare.io/s/jujxrzxvhnabejpqtlozozcytn2q/test/storj-whitepaper-v3.pdf

Trying to download the file will result in an Access Denied error:
https://link.storjshare.io/s/jujxrzxvhnabejpqtlozozcytn2q/test/storj-whitepaper-v3.pdf?download

**Comment by kaloyan-raev** [comment]
@YurkoWasHere Not that we are aware of a possible UX issue your may run into: https://github.com/storj/gateway-mt/issues/274
We will fix it in a later release.
