### ISSUE TITLE
object already exists error

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-mt#214]
Some S3 clients seem to encounter an "object already exists" error, which has been reported at least in the forum post https://forum.storj.io/t/error-copying-files/18945, but also Orbiter was having some troubles with this as well. From an Orbiter log:

```
checkers.Uplink{Satellite: "12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S@us1.storj.io:7777", Bucket: "uptime-checks", Key: "uplink-tests/from_eu_orbiter_0/4M", Size: 4.0 MiB} StateChangeThreshold: 3 recovering soon: 1/3
FAIL (2022-06-27 14:17:05 UTC)

orbiter warning: uplink: stream: metaclient: metabase: object already exists
	storj.io/uplink/private/metaclient.(*Client).Batch:1500
	storj.io/uplink/private/storage/streams.(*Store).Put:217
	storj.io/uplink/private/stream.NewUpload.func1:47
	golang.org/x/sync/errgroup.(*Group).Go.func1:57
```

It can be replicated when uploading the same key concurrently, and a unique violation occurs at the database: https://github.com/storj/storj/blob/4791ba5d50aba5776f9a14af8ffaf5f813e6e6c8/satellite/metabase/commit.go#L195. This does not happen serially, because the existing record is deleted before the new one is added, but a race condition occurs with concurrent requests. I'm not sure what clients are doing at the time they get the error though. Are they sending uploads concurrently, or is there something else going on?

Metainfo team has issues in their backlog (https://github.com/storj/storj/issues/4871 and https://github.com/storj/storj/issues/4788) which may fix the problem to be more an atomic put like AWS S3 (which we'd need to be compatible anyway), but we don't know when that will be implemented. More information on AWS S3 consistency model can be found in their docs, including an example of "last writer wins": https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel

For the moment with the current information, I think we could:

* Try to replicate the Duplicacy client encountering this error, and seeing what requests it's trying to make.
* Implement a workaround on gateway so that users will not be blocked by this error.

**Comment by amwolff** [comment]
From sprint planning: if the workaround is too complex, let's leave this at the investigation stage.

**Comment by halkyon** [comment]
So after some investigation with Paul, we discovered:

* We thought Traefik could be duplicating requests: https://github.com/traefik/traefik/issues/8871
* Looking at gateway logs, it appeared as though the client got an interruption (e.g. network issues?) while uploading the object. What we saw after that were requests made to the same key 4 times within 2.5 seconds that got the "object already exists" error.
```
2022-07-11T21:10:38.768Z	code": 499,	content-length": 1607028, "	duration": "25.154301169s"	X-Real-Ip=x.x.x.x"
2022-07-11T21:12:11.037Z	code": 500,	content-length": 1607028, "	duration": "522.21753ms"	X-Real-Ip=x.x.x.x"
2022-07-11T21:12:12.399Z	code": 500,	content-length": 1607028, "	duration": "586.821696ms"	X-Real-Ip=x.x.x.x"
2022-07-11T21:12:13.609Z	code": 500,	content-length": 1607028, "	duration": "635.098604ms"	X-Real-Ip=x.x.x.x"
2022-07-11T21:12:14.549Z	code": 500,	content-length": 1607028, "	duration": "406.953432ms"	X-Real-Ip=x.x.x.x"
```
* The user was using `s3://` backend in Duplicacy, which has retries failed requests, but does not have backoff or delay: https://github.com/gilbertchen/duplicacy/blob/master/src/duplicacy_s3storage.go#L233.
* There's another backend "S3 compatibility/minio" in Duplicacy which uses a different client, one which has a delay between requests: https://github.com/gilbertchen/goamz/blob/master/aws/attempt.go

The theory is that because the requests were made so quickly without any delay, the retries were quickly used up from encountering the same "object already exists" error, but there weren't enough retries left with sufficient delay in order to get a success.

I mentioned to the user they could try the `s3c` backend to see if that improves things: https://forum.storj.io/t/error-copying-files/18945/19. For now though, I think we can close this and wait until object consistency is fixed in https://github.com/storj/storj/issues/4788.
