### ISSUE TITLE
DNS resolution failures with edge services @ EU1

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#223]
For some reason, we keep having a lot of unmapped errors that seem to look like DNS resolution failures in one region only (EU1).

For example:

`uplink: metaclient: rpc: tcp connector failed: rpc: dial tcp: lookup ap1.storj.io on 127.0.0.1:53: read udp 127.0.0.1:17256->127.0.0.1:53: i/o timeout`

Why isn't the resolver caching these queries? It seems impossible for the timeout to happen at the loopback level, so it must be the resolver failing to forward the query.

**Comment by stefanbenten** [comment]
The mentioned change ^ has a currently hit rate of 98.8% on the app servers. Is that good enough to close the ticket for now? @amwolff @pwilloughby

**Comment by stefanbenten** [comment]
Additional note: current cache size is only 2500 nodes (without much load on those systems)

**Comment by amwolff** [comment]
ok, this looks good enough to close it. Thanks, @stefanbenten!
