### ISSUE TITLE
Understand most important factors for time to first byte metric

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#228]
Time to first byte is one of the most important user-facing metrics that is currently tracked on Edge servers.  We see predictably different values in different PoPs, in what seems like larger than be explained just by latency caused via network wire times alone.  [The function_times metric for `DialContext` is a good way to see pure internet latency differences.]

Storj needs to understand [and/or articulate] the major factors contributing to higher region-specific latency, to attempt to offer our lowest latencies for all regions.  We're specifically interested in api='GetObject' AND status_code='200', and most notably on the US1 PoP, where the distribution seems almost bimodal.

Bonus points awarded if you can understand what issues (non status_code='200') lead to long waits.

Acceptance criteria is that Bill believes you.  :D

**Comment by wthorp** [comment]
There's a strong inverse relationship between the `function_times` metric for `DialContext` where `kind="failure"`. and time to first byte.  The time difference between `DialContext` failure and success pretty well matches the TTFB deltas.

**Comment by wthorp** [comment]
Its important to note that this doesn't appear to correspond to the `function_time` for `GetObjectNInfo`.  I think this means the issue is either in Minio's handlers or in our wrappers for it.  

```
// GetObject
bucket.Methods(http.MethodGet).Path("/{object:.+}").Handler(
	limit(MaxClients(CollectAPIStats("getobject", HTTPTraceHdrs(api.GetObjectHandler)))))
```

**Comment by amwolff** [comment]
Closing this as we fixed many things before we got to this issue, and the observations that led to creating this issue are no longer there.
