### ISSUE TITLE
Fail faster on Dial Timeout

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#229]
Gateway-mt and likely Linksharing don't currently timeout quickly during `DialContext` functions when dialing fails.  [At a higher level, we see this in the rpc pool failure stats.)  It seems like we use a derived context to timeout more quickly, but it might be cleaner to add a timeout to those functions

**Comment by shaupt131** [comment]
Acceptance Criteria:

1. Investigate and list all the places we need to add a timeout.
2. Determine how long is acceptable before a timeout occurs
3. Make the timeout length configurable

**Comment by ferristocrat** [comment]
@amwolff - does the above change include a default timeout for Gateway-MT as well? Looking at the numbers for Gateway-MT, we could use faster timeouts there as well...
