### ISSUE TITLE
Review CertMagic library

### ISSUE THREAD

**Issue by shaupt131** [storj/gateway-mt#233]
### Goal
What are you trying to achive, and why?

- We need to review CertMagic according to our [internal dependency review process](https://github.com/storj/docs/blob/main/code/Dependencies.md).

### Acceptance Criteria
What is the outcome of the task/spike? Examples include new tickets, documentation, etc.

- CertMagic is reviewed and issues are fixes (if any).

### Links
Add any links or documents that are relevant to understanding the outcome of this task. (PRDs, Blueprints, Slack Discussion, etc)

 - https://github.com/storj/docs/blob/main/code/Dependencies.md

**Comment by pwilloughby** [comment]
see https://docs.google.com/document/d/1gwPN5xMIcKwTkRKtWLFnzpPcuuLjVKHDjYDYtwO4bUc/edit#

**Comment by shaupt131** [comment]
@storj/edge-team Please review Paul's list above and provide any feedback.

**Comment by amwolff** [comment]
I looked through Paul's review. It seems solid. There are some pending comments by Egon, but otherwise, it's good to go, I think.
