### ISSUE TITLE
Feasibility of using providers other than LetsEncrypt?

### ISSUE THREAD

**Issue by shaupt131** [storj/gateway-mt#236]
### Goal
What are you trying to achieve, and why?

- We are trying to determine if there would be anything that we could use that would be better than LetsEncrypt. 

### Acceptance Criteria
What is the outcome of the task/spike? Examples include new tickets, documentation, etc.

- Review the list linked below and provide some highlights of the ones that would support tls-alpn-01.  We're specifically interested in:
    - Rate limits
    - Overall limits
    - Price
    - Ease of limit changes
    - Size of the certificates

### Links
Add any links or documents that are relevant to understanding the outcome of this task. (PRDs, Blueprints, Slack Discussion, etc)

 - a list of providers: https://poshac.me/docs/v4/Guides/ACME-CA-Comparison/

**Comment by pwilloughby** [comment]
I've ranked the CAs from what I think are most suitable to least suitable for our use case.
1. [Google](https://cloud.google.com/certificate-manager/docs/public-ca)
2. [Let's Encrypt](https://letsencrypt.org/)
3. [BuyPass](https://www.buypass.com/)
4. [ZeroSSL](https://zerossl.com/)
5. [SSL.com](https://www.ssl.com/)

Google Public CA edges out Let's Encrypt with simplified and permissive rate limits but it's currently "pre-GA" (this may change by the time we go to production).  ZeroSSL has no rate limits but their documentation looks limited and I ran across several posts complaining about poor availability which their [status page](https://status.zerossl.com/7090875/2022/08) seems to confirm. 

We are able to use multiple CAs. Using the top two or three CAs together seems like it would make for a pretty robust setup.  It's easy to switch between CAs or change the order they are used so I don't think extensive research here is really necessary.

**Comment by shaupt131** [comment]
@storj/edge-team From Pauls research, it sounds like Google CA might be our best option.  Did we double check all of the areas of interest in the AC above (rate limits, overall limits, price, ease of limit changes, size of certs)?  If so, any objections from the team?  If not, I think ticket is done.

**Comment by halkyon** [comment]
Looks good to me.

**Comment by amwolff** [comment]
Same, LGTM.
