### ISSUE TITLE
[Linksharing TLS] Ensure only pro accounts can use custom domains over TLS

### ISSUE THREAD

**Issue by shaupt131** [storj/gateway-mt#241]
### What is the problem/pain point?

- Given that custom domains over TLS is more of a premium feature that brings additional costs to maintain, we want to be able to restrict access to pro accounts.

### Who is impacted?

- All customers technically, but will not impact any existing use given that this is a new feature

### What is the impact?

 - If we don't limit this feature, we run the risk of abuse. It also makes it harder to charge differently in the future if we don't restrict access.

### Why now?

- Can't go live without it

### User Story

- As a Storj pro account user creating a linkshare I want to be able to enable a custom TLS domain, so that linkshare requests using my domain are secure.

### Acceptance Criteria

- Users can "opt in" to custom TLS domain via a flag in the share command (`uplink share --dns downloads.example.com sj://files --SOMEFLAG`)
- If the user does not have a pro account, the flag is ignored

### Engineering Discussion/Considerations
 - Will there be too many requests to the "source" of information telling us if the account is "pro" or not?
   - This won't need to happen on EVERY linkshare request, only for requests that trigger the initial cert generation or cert renewal 
   - Do we need to consider repeated requests that include the TLS flag for non-pro accounts? How might we prevent this from negatively impacting our service?
 - What if Satellite code needs updating?
   - We should make the change and submit the PR

**Comment by halkyon** [comment]
Seems a bit unclear how we'd implement this so only certain accounts can use it. Maybe we need to add something to uplink to get account information?

**Comment by shaupt131** [comment]
Moving to an enhancements milestone for further consideration.  Not required for MVP.

**Comment by ferristocrat** [comment]
> Seems a bit unclear how we'd check for only certain accounts to use the feature. Maybe we need to add something to uplink to get account information? What is the motivation for only certain accounts to be able to use it?

Updated the description to hopefully address all these things

**Comment by shaupt131** [comment]
Sounds like my comment above about this not being required as MVP is no longer relevant?

**Comment by ferristocrat** [comment]
Separate meeting/session. Likely break this down into some spikes.

**Comment by mobyvb** [comment]
related to https://github.com/storj/storj/issues/5296

**Comment by amwolff** [comment]
From sprint planning: one idea is to introduce a satellite-signed portion of access grant that could be used for this.
