### ISSUE TITLE
[Linksharing TLS] Metrics for number of customers currently using custom domains

### ISSUE THREAD

**Issue by shaupt131** [storj/gateway-mt#244]
### Goal
What are you trying to achive, and why?

- How many and which customers are using custom domains?

### Acceptance Criteria
What is the outcome of the task/spike? Examples include new tickets, documentation, etc.

-

### Links
Add any links or documents that are relevant to understanding the outcome of this task. (PRDs, Blueprints, Slack Discussion, etc)

- Looking at logs and filtering them might be a good idea
    - Do we we have any metrics that we could use?

**Comment by halkyon** [comment]
I had an idea to use Marton's collector for seeing which macaroon heads are being used in custom domain requests: https://review.dev.storj.io/c/storj/gateway-mt/+/8437. At the moment it only keeps in-memory, but we can have it send to somewhere using the `eventstat.Registry` functionality. I'm still getting familiar with this to see if it'll be suitable or not.
