### ISSUE TITLE
Blueprint of auto-deploy to staging

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#25]
JT and Kaloyan think that because the "edge" services like Gateway, Auth, and Link sharing are stateless, that they'd be a good place to start working on a continuous release process.  Write up a plan to have these automatically deploy to staging on a successful build.

Make sure Krista is involved.

**Comment by amwolff** [comment]
Closed by 16d0f213158b2f8a38932442c42b93ebb503b2fa.
