### ISSUE TITLE
Gateway-MT Production Debugging

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#251]
### What is the problem/pain point?

- When customers are first onboarding to Storj's S3 Compatible Gateway-MT, sometimes their S3 configuration needs some tweaking to get everything working correctly.

### Who is impacted?

- Customers using Gateway-MT, as well as our customer facing teams supporting their onboarding.

### What is the impact?

- Storj Employees such as Solution Engineers (and other team members, such as support) have no way to help customers identify gaps in their Gateway-MT S3 configuration.

### Why now?

- As we onboard more and more customers we need to be more automated with how we support customers, as well as identify potential gaps in our feature parity with the S3 standard.

### User Story

- As a Storj Solution Engineer, I want to be able to see request details for Gateway-MT requests so I can better help customers as they are switching their S3 workloads to Storj DCS.

### Acceptance Criteria

- Customer can toggle on the ability for a Storj Solution Engineer to read full request details
  - Two ideas that have been discussed are either:
    1. using a separate endpoint such as test.gateway.storjshare.io 
    2. Having some additional param to trigger this
  - The Storj Solution Engineer should be able easily retrieve the request details
    - One idea that was floated was using something like a request id: https://github.com/storj/gateway-mt/issues/249

### Success Metrics

- Customer time-to-value decreased (due to faster onboarding/troubleshooting)
- Less time from Storj engineers manually triaging S3 compatibility related customer problems

### Example Request Details
```json
{
  "protocol": "HTTP/1.1",
  "method": "PUT",
  "host": "ngb1-hz.stargate.staging.tardigradeshare.io",
  "code": 501,
  "user-agent": "Boto3/1.17.64 Python/3.9.4 Linux/5.4.170+ Botocore/1.20.80 Resource",
  "api": "CopyObjectPart",
  "error": "",
  "request-id": "16F2AFCJS90AFE7B",
  "encryption-key-hash": "c9103e8849fd047e35a471178hd02d12af3ba737602c1d70e31a4d8f61162dd6",
  "content-length": 0,
  "written": 342,
  "duration": "799.056121ms",
  "query": [
    "uploadId=5TSjjoRP8u5933DDH9cL8iXzyGe4hLafWxaApibGPKw9wCeoGVW7nHwtfPbbd3JtfA2ekogbHeMRgYrj6cHBakc8qjKQ4Tcrhai4EAAa6N7pf4tKbVk5mSSpEU7ftSrLontG8Li6aeoNgpBsWaGNac1XmdMmsrFjg98835dC2pJXqPHesswqJMNMDVcPk4cyCu3FS31pKHSa1vrggqkks3M",
    "partNumber=1"
  ],
  "req-headers": [
    "X-Real-Ip=10.11.12.5",
    "X-Amz-Date=20220526T150055Z",
    "X-Forwarded-Host=ngb1-hz.stargate.staging.tardigradeshare.io",
    "X-Forwarded-Proto=https",
    "X-Forwarded-Server=stargate-0",
    "X-Amz-Copy-Source=[...]",
    "X-Amz-Copy-Source-Range=bytes=0-8388607",
    "X-Forwarded-For=10.11.12.5",
    "X-Amz-Content-Sha256=e3b0c44298fc1c149afbf4c1126fb92427ae41e4649b934ca495991b7852b855",
    "X-Forwarded-Port=443",
    "User-Agent=Boto3/1.17.64 Python/3.9.4 Linux/5.4.170+ Botocore/1.20.80 Resource",
    "Content-Length=0",
    "Accept-Encoding=identity",
    "Authorization=[...]"
  ],
  "rsp-headers": [
    "Content-Type=application/xml",
    "Content-Length=342",
    "Vary=Origin",
    "X-Xss-Protection=1; mode=block",
    "Content-Security-Policy=block-all-mixed-content",
    "X-Amz-Request-Id=16F2AFC0D89AFE7B",
    "Server=MinIO",
    "Accept-Ranges=bytes"
  ]
}
```

- [x] storj/infra#3386
- [x] storj/infra#3387
- [x] #278

**Comment by ferristocrat** [comment]
@amwolff @halkyon - I think the aggregated logging solves this need, right?

**Comment by amwolff** [comment]
@ferristocrat @ferristocrat Yes. This would be one of the side effects of implementing aggregated logging.

**Comment by amwolff** [comment]
We should probably break this issue into several tickets organized into a milestone.
