### ISSUE TITLE
Fetching access grants from Auth Service seems slow

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#252]
## Expected Behavior

Gateway-MT and Link Sharing Service should be able to fetch access grants in 10-20 milliseconds.

## Current Behavior

Data suggests it's taking a lot longer, but it may be only for specific hosts. Custom Link Sharing Service deployments seem to be taking forever (100-200-300 ms) while hosts in AP1, EU1, and US1 never exceed an average of 20 ms or so. What's going on there? Does it take that long to dial Auth Service for these custom hosts? Why do these hosts even have to reach out to Auth Service, as they should only have one Access Key ID in their cache? Again what's going on there?

## Steps to Reproduce

```sql
SELECT last("recent") AS "mean_recent" FROM "v3_stats_new"."autogen"."function_times" WHERE time > :dashboardTime: AND "name"='(*AuthClient).Resolve' AND "kind"='success' GROUP BY time(:interval:), * FILL(null)
```

## Context (Environment)

Prod

## Possible Implementation

Maybe we should use DRPC for `GET` calls to Auth Service (and, of course, connection pooling)?

**Comment by aishwaryasharmaccoew** [comment]
Link to the data points for cached and non cached access grants
https://docs.google.com/spreadsheets/d/1n07o1O_mIyXvtUI_-RJPjnAzqNrAkPIbr0QmfeI0UWM/edit#gid=0

**Comment by stefanbenten** [comment]
Our Hetzner deployments do not make use of their own Authservice locally, rather than ask the datacenters via the global domain.
This can be slower given they have to initiate a connection and such.
I do agree, they should not need to; their access grant should be rather static.

**Comment by halkyon** [comment]
are we sure we're looking at the right metric? ResolveWithCache is used everywhere, but Resolve is for fetching from auth uncached. If you change the query to ResolveWithCache there are far more hits to this function than Resolve, which is expected.

**Comment by aishwaryasharmaccoew** [comment]
I was initially manually trying to log Resolve, but then following [this](https://storj.slack.com/archives/C0196DNUML0/p1666977450488149) I moved to collecting ResolveWithCache times.
 I guess the idea was to log the overall runtime of resolveWithCache excluding the network calls for cached and non cached access grants.
It might be useful to check how often Resolve gets called for a set of requests?
what would you suggest?

**Comment by halkyon** [comment]
Yes, according to metrics Resolve is not called that often, so it's not reaching out to an authservice that often and implies it's mostly using the cache. There could be cases of new access grants being derived periodically for content so it has to resolve those from uncached, hence why there are still some requests going to the auth service. ResolveWithCache seems to be very fast in all cases.

The uncached 200ms request seems unavoidable unless we run auth closer to the linksharing/gateway-mt on the affected custom services, as Stefan pointed out.

**Comment by aishwaryasharmaccoew** [comment]
Collected some stats in the below document to try and find the cause
https://docs.google.com/document/d/1lVqYMJTUduVwtxTHnjyGJQAMQNDQN5orBS_-RfIQAdw/edit?usp=sharing
