### ISSUE TITLE
We should get rid of `linkname` hacks from Gateway-MT

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#269]
Gateway-MT pulls our MinIO fork (storj.io/minio), and to implement multi-tenancy, it references some functions/methods that are not exported by using the `linkname` trick. However, this hack has its limitations, and we recently discovered that we rely on the build toolchain's side effects utilizing it. For example, in `pkg/minio/expose-handlers.go`, we expose methods which is not officially supported (https://github.com/golang/go/issues/52774#issuecomment-1120439115).

We should get rid of these and actually modify the fork now that it's updated to the latest possible version. Otherwise, this could bite us in the future further than it recently did.

**Comment by halkyon** [comment]
As part of doing this, I discovered we're trying to expose `globalIsSSL` but that property doesn't exist in minio anymore. It's called `globalIsTLS` now! I assume we missed that during the latest minio upgrade. Yet another reason to get rid of these `linkname` hacks!
