### ISSUE TITLE
Services need to signal they're shutting down through the health check endpoint

### ISSUE THREAD

**Issue by stefanbenten** [storj/gateway-mt#271]
### What is the problem/pain point?

Upgrading services in prod cause blips in monitoring due to services shutting down too quickly before the load balancer evicts the container from rotation.

### Who is impacted?

Customers, internal monitoring, etc. -> basically everyone

### What is the impact?

Failure of requests and potential blips in the availability of the service.

### Why now?

The bigger the scale, the higher the impact of not having services to route requests to.

### User Story

As an operator, I expect the health check endpoint should indicate that the endpoint is going down first, then wait X seconds, and then shut the binary down gracefully after having all requests handled.

### Acceptance Criteria

Shut down works as described above and timeouts are configurable.

### Success Metrics

We should be able to 0 downtime upgrades with a 2+ binary setup with a load balancer in front.

**Comment by NiaStorj** [comment]
Can we get an estimation on this?

**Comment by NiaStorj** [comment]
@pwilloughby please see my note above
