### ISSUE TITLE
Linksharing: Download button shows empty page instead of error

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/gateway-mt#274]
When sharing a file with list-only access grant the Download button in Linksharing does not have the correct behavior.

## Expected Behavior
The browser should display an error page with an Access Denied error.

## Current Behavior
The browser displays an empty page.

## Possible Solution
The download button is implemented as an `<a>` HTML tag with a hardcoded `download` property, which forces the browser to download the file, which fails due to the lack of permissions. If I manually remove the `download` property, the browser displays the expected error page, which is the correct behavior.

The `download` property should be set according to the access grant permissions. Or maybe the download button should even be disabled.

## Steps to Reproduce
1. Share a file with list-only permissions, i.e. with `--disable-reads` flag.
2. Open it with the linksharing service, e.g. https://link.storjshare.io/s/jujxrzxvhnabejpqtlozozcytn2q/test/storj-whitepaper-v3.pdf
3. Click the Download button.

## Context (Environment)
This issue may lead to bad UX, as the user may not understand why they cannot download the file as the appropriate error page is not displayed.

The described behavior is observed in Firefox. It may look different in other web browsers.

**Comment by ferristocrat** [comment]
Shouldn't this be an update to the satellite ui rather than gateway? @mobyvb

**Comment by mobyvb** [comment]
@ferristocrat link.storjshare.io is the gateway UI, not the satellite UI
