### ISSUE TITLE
Make Link Sharing Service fail fast with CertMagic enabled

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#276]
### Goal

Instead of waiting for the first requests to come in with CertMagic enabled (e.g. for Custom Domains @ TLS), LSS should fail fast after launch if the configuration is invalid.

### Acceptance Criteria

The service is capable of recognizing an invalid configuration and aborting the startup.

### Links

- https://review.dev.storj.io/c/storj/gateway-mt/+/8602/comment/73ac54fe_95be3a54/

**Comment by halkyon** [comment]
One idea I had is to programmatically test permissions, e.g. https://stackoverflow.com/questions/72407618/how-do-i-check-that-a-google-cloud-service-account-has-a-particular-permission-p.

Something like `client.Bucket("myBucket").IAM().V3().TestPermissions(ctx, "storage.objects.create")`. Unfortunately that uses the https://pkg.go.dev/cloud.google.com/go/storage package which we don't currently import (at least not directly, but we do indirectly), and it'd be a shame to add another dependency. There might be an easy way to call the IAM API without needing the entire dependency though.
