### ISSUE TITLE
Use new cert-magic logic in authservice and gateway-mt

### ISSUE THREAD

**Issue by mjpitz** [storj/gateway-mt#279]
As part of our work around scaling our edge services, we started to look into how to improve operations around our ingress. Currently, we terminate TLS using an L7 proxy which requires data to be unpacked and resent to the destination server. In digging around some of our TLS code, I found that authservice, gateway-mt, and linksharing aren't using the same mechanisms. It would be nice if they all used the new cert-magic functionality as it would ease our migration to terminating TLS at the application layer. To prevent excessive requests and re-issues against the ACME server, we can obtain a current copy of the certificate used from our proxy and upload it to the bucket directly. Then when the logic is enabled, it will re-use the existing cert instead of requesting a new one.

Acceptance criteria:
- [ ] cert-magic can be enabled (`--cert-magic.enabled`)
- [ ] A service key file can be provided for persisting certificates (`--cert-magic.key-file=/app/keys/gcp.json`)
- [ ] A bucket can be specified (`--cert-magic.bucket=$NAME`)

**Comment by NiaStorj** [comment]
@amwolff @mobyvb for visibility

**Comment by halkyon** [comment]
I would also add to acceptance that wildcard certs are provisioned/renewed, because we need those for virtual host style S3 requests. That also means we need to do a DNS ACME challenge to get those, as other challenges (like TLS-ALPN which we're doing for linksharing) don't support it.

**Comment by amwolff** [comment]
This issue is currently blocked on:

- #290 
- #291
