### ISSUE TITLE
[Linksharing TLS] preload existing certs to storage bucket

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-mt#280]
### Goal

When we deploy the new Linksharing certmagic feature, the existing certs for `--public-url` need to be in place first so we can avoid downtime. One way to overcome this is to preload the existing certs into the storage bucket certmagic uses.

### Acceptance Criteria

* Existing certs for Linksharing are copied into the certmagic storage bucket
* Linksharing TLS request using those certs is successful (i.e. certmagic can find and successfully read the existing certs and keys)

## Ideas

* Write a tool (or include in Linksharing itself?) something that uses certmagic and does a DNS challenge, and puts the cert in the right place in the storage bucket. TODO: can the DNS challenge can be switched over to TLS-ALPN for renewals after the initial certificate has been obtained?
  * This tool might be helpful if we need to repeat the preload process for gateway and auth in future: https://github.com/storj/gateway-mt/issues/279
* Use an existing tool like certbot with DNS challenge, then manually copy in the cert and key to the right place in the storage bucket.
* Find the existing certs in production and copy them to the storage bucket.

### Questions

* Does certmagic need anything else in place for this to work, or can the crt and key file just be copied over directly?
  * certs created through certmagic have a json file in the storage containing an issuer URL. Is that needed for the existing certs, or can we reconstruct the file ourselves?
  * It might be worth checking `loadManagedCert`: https://github.com/caddyserver/certmagic/blob/a46420babdc80437ac128dc3942ada18be0786db/certificates.go#L139

**Comment by pwilloughby** [comment]
Since we now have DNS challenges in gateway-mt maybe linksharing could be configured to use DNS challenges for the public urls as well.  I like the idea of the public url certs being issued or fetched into cache at startup, it also fixes this preload issue.

**Comment by halkyon** [comment]
> Since we now have DNS challenges in gateway-mt maybe linksharing could be configured to use DNS challenges for the public urls as well. I like the idea of the public url certs being issued or fetched into cache at startup, it also fixes this preload issue.

Sounds good to me I think!
