### ISSUE TITLE
Relax content-disposition: attachment requirements for linksharing

### ISSUE THREAD

**Issue by jtolio** [storj/gateway-mt#284]
When loading an image via the /raw/ handler for linksharing, it's a bit surprising, even with our security measures, that the content-disposition is marked as an attachment and thus triggers a download, instead of letting you view the image in your browser.

Here's an example of user confusion: https://forum.storj.io/t/mastodon-loaded-assets-opening-as-attachments-instead-of-inline/20875 or https://github.com/storj/customer-issues/issues/457.

We force content-disposition: attachment to prevent phishers from hosting content on our domain, but perhaps we're being too strict.

Can we relax this policy for some file types? We don't want to create an escape hatch where a phisher could use this to serve web content on our domain. If content is identified as specific image mime types, can we be sure that that is safe to add to an allowlist? (SVGs can embed javascript).

In the most narrow interpretation, it would be nice to allow GIF, PNG, JPG files (that we are sure are GIF, PNG, or JPG files) to render instead of forcing a download.

**Comment by kmozurkewich** [comment]
+1 for this.  We've run into this issue for years.
