### ISSUE TITLE
Handling HTTP Traffic to Linksharing

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#288]
### Goal

- Determine how we want to handle HTTP request to our linksharing domain (both public and custom domains)

### Acceptance Criteria

- What is the default behavior?
  - What happens when someone requests our default linkshare domain using HTTP (**_http_**://link.storjshare.io/s/hjklsadjfklsdfjklsdfjkllsd/demo-bucket/Big%20Buck%20Bunny%20Demo.mp4)
  - Do we redirect to HTTPS?
- Should we disable HTTP entirely?

### Links

 -

**Comment by ferristocrat** [comment]
@amwolff - created this as a placeholder... feel free to update the description

**Comment by amwolff** [comment]
@ferristocrat I think we should close this one. We need to support plaintext traffic to LSS for backwards compatibility.

**Comment by jtolio** [comment]
in terms of our backwards compatibility, we could require TLS for things that are specifically requesting link.storjshare.io and be okay. the server itself needs to support non-TLS requests for non-pro custom domains without TLS, but the decision to require TLS for link.storjshare.io could be made after we determine that it's not a custom domain.

**Comment by kaloyan-raev** [comment]
PRs for HTTP -> HTTPS redirects:
- https://review.dev.storj.io/c/storj/gateway-mt/+/11013
- https://review.dev.storj.io/c/storj/gateway-mt/+/11015

**Comment by kaloyan-raev** [comment]
HTTP --> HTTPS redirect is now enabled in production for both base and custom domains.
