### ISSUE TITLE
Resolve dependency conflict with google.golang.org/grpc

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#291]
### Goal

To pull in github.com/libdns/googleclouddns for #279 (for CertMagic to request a certificate for a wildcard domain from Gateway-MT) we need to resolve the following conflict:

```
go: finding module for package github.com/libdns/googleclouddns
go: found github.com/libdns/googleclouddns in github.com/libdns/googleclouddns v1.1.0
go: finding module for package google.golang.org/grpc/naming
storj.io/gateway-mt/pkg/minio imports
        storj.io/minio/cmd imports
        go.etcd.io/etcd/clientv3 tested by
        go.etcd.io/etcd/clientv3.test imports
        go.etcd.io/etcd/integration imports
        go.etcd.io/etcd/proxy/grpcproxy imports
        google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.52.0), but does not contain package google.golang.org/grpc/naming
```

#### Context

I pushed the last change to terminate TLS with CertMagic in Gateway-MT (and other services are already done): https://review.dev.storj.io/c/storj/gateway-mt/+/9301. The only problem is that I can't easily import github.com/libdns/googleclouddns because it imports gRPC. gRPC is also imported by MinIO in a different version that, as I found out, is incompatible with the version that the package imports. So this locked me out. I think I will just remove etcd integration within MinIO that we never used and never will be instead of rewriting that package in pure HTTP github.com/libdns/googleclouddns imports Google Cloud SDK that imports gRPC probably because it communicates over RPC instead of HTTP for some of its services).

### Acceptance Criteria

The conflict is resolved, presumably through removing the stale dependency from storj.io/minio.

### Links

tbd

**Comment by NiaStorj** [comment]
reviewing tickets: can I mark this as deployed? @halkyon or @amwolff
