### ISSUE TITLE
Document How Linksharing Generates Geolocation Map from IPs

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#292]
### Goal

- Document how linksharing currently generates the geolocation data for an object and create tickets and/or brief design for how we might enable users to access this data

### Acceptance Criteria

- Document steps to generate GeoJSON from [GetObjectIPSummary](https://github.com/storj/uplink/blob/main/private/object/object.go#L34-L35) used by linksharing to generate the object [Dot Map](https://github.com/storj/dotworld)
- Write up tickets or doc for how we will expand this to generate GeoJSON for a given bucket, prefix, or single object

### Links

 - https://github.com/storj/dotworld
 - https://github.com/storj/uplink/blob/main/private/object/object.go#L34-L35

### Notes
Two running ideas for how to do this:
1. Add endpoint to Linksharing that returns GeoJSON
2. Add new service that takes bucket, prefix or file as input and separate bucket as output -- GeoJSON gets dumped into output bucket (on interval)
   - Create new microservice (GCP to deploy quickly?)
   - Schedule GeoJSON dumps weekly (using https://cloud.google.com/scheduler/docs/creating?)

**Comment by ferristocrat** [comment]
@amwolff - here's a placeholder issue within the Milestone created for https://github.com/storj/roadmap/issues/51

**Comment by kaloyan-raev** [comment]
Here is a gist with an example program on how to generate a GeoJSON for an object or a prefix: https://gist.github.com/kaloyan-raev/c3dd95f2347a8d49f882b5576508f294

The code follows what the Linksharing does, but without requesting it. It requests only the satellite and a local MaxMindDB.

This code does not require any new API - it just uses what is currently available in production.

**Comment by kaloyan-raev** [comment]
Here is an example output for a single object:
```json
{"type":"Feature","geometry":{"type":"MultiPoint","coordinates":[[12.5113,41.8919],[-0.093,51.5164],[2.3387,48.8582],[13.566,52.4608],[15.6167,58.4167],[-6.7679,62.0061],[9.491,51.2993],[1.1069,41.1561],[-1.5167,54.9],[-82.7593,28.0684],[-73.5794,45.5063],[-84.1534,33.454],[30.2642,59.8944],[4.2345,50.7338],[37.6068,55.7386],[19.6913,46.9062],[14.156,50.7304],[-122.6929,45.5073],[-86.1295,39.9714],[37.6068,55.7386],[-97.822,37.751],[-118.5035,34.0271],[2.3387,48.8582],[-74.4592,40.8229],[24.997,45.9968],[37.6068,55.7386],[30.5167,50.4333],[8.7505,51.0021],[2.3488,48.8534],[30.2642,59.8944],[22.2214,50.9249],[37.6068,55.7386],[9.2769,53.2966],[9.491,51.2993],[-0.2491,51.5943],[9.491,51.2993],[2.3072,48.9012],[2.3387,48.8582],[9.491,51.2993],[8.7667,56.2],[-2.45,42.4667],[9.491,51.2993],[-3.7026,40.4165],[26.1691,44.418],[-97.8203,30.1746],[-93.6694,41.6244],[2.3488,48.8534],[28.8575,47.0056],[4.4456,52.0182],[-80.2318,25.8119],[-97.822,37.751],[-122.9093,49.2183],[28.1706,-25.8744],[-97.822,37.751],[9.7688,49.0014],[-6.3437,38.9161],[26.1,44.4333],[24.7323,59.433],[9.491,51.2993],[3.178,50.6974],[36.58,50.61],[-3.7026,40.4165],[4.5501,50.4835],[37.6068,55.7386],[131.7551,44.1586],[-9.3923,38.7161],[16.35,48.3],[2.1864,48.8782],[26.0602,44.4914],[-0.093,51.5164],[-79.3716,43.6319],[37.6068,55.7386],[10.262,56.4893],[21.1992,48.6865],[18.0009,59.36],[-6.9495,37.2714],[-85.3755,32.6414],[-70.7694,-33.5172],[2.3387,48.8582],[-97.7972,30.2095]]},"properties":{"objects":1,"pieces":87,"reliable pieces":80,"segments":1,"storage nodes":80}}
```
You can copy and paste this JSON into https://geojson.io to render it on the globe.

![image](https://user-images.githubusercontent.com/468091/214049230-af7ac42b-5960-4b21-bc8e-1e2366643388.png)

**Comment by kaloyan-raev** [comment]
However, it's essential to understand this feature's motivation better.

If the "data set" is just a few hundred segments or more, it will saturate the entire Storj network, i.e. almost every storage node would have a piece of the data. In such a case, it's just wasteful to query the satellite for the IP addresses. We already publish the Geo coordinates of the entire Storj network to our public stats: https://stats.storjshare.io/nodes_geo.json

**Comment by ferristocrat** [comment]
Closing as Kaloyan's [gist](https://gist.github.com/kaloyan-raev/c3dd95f2347a8d49f882b5576508f294) covers this
