### ISSUE TITLE
Auth shouldn't signal internal server errors on invalid input or likewise

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#305]
# Context/Overview

I want to jot down a few improvements for auth service and then what status codes gateway and linksharing pass from it:

1. we can reduce 5xx errors on Auth's side to a minimum. It looks slightly bad when we respond with these to bad input
   - ~on PUTs, we respond with 5xx when someone posts a malformed access grant. We should respond only in case of genuine database errors~ Fixed in https://review.dev.storj.io/c/storj/gateway-mt/+/9714
     - ~this probably warrants a new error type inside auth's code~
   - on GETs, we respond with 5xx errors when auth cannot reach other nodes on lookup when specific access hasn't been replicated to it yet
     - this triggers exponential backoff within auth client and makes gateway/linksharing stall on such requests
     - we should probably just return 401/404 and hasta la vista
     - this means peeking wouldn't be retried if it's unsuccessful on the first try for a specific Access Key ID
   - ~on GET for the invalidated record, auth returned 5xx instead of a reasonable status code; Sean just fixed this (thanks!)~ Fixed in https://review.dev.storj.io/c/storj/gateway-mt/+/9578
2. ~Related to 1.3, Stefan gave an idea that maybe we should return 451 (Unavailable Due to Legal Reasons) instead of 401/404 when the record is invalid~ 

# Acceptance Criteria

Completing the work on this issue means adjusting current behavior to match expected behavior, as indicated by the list above.

**Comment by amwolff** [comment]
No. 2 is a bit imprecise in whether to change the behavior or not. It might warrant reaching out to the product and/or legal to confirm it's reasonable to change that. /cc @ferristocrat

**Comment by amwolff** [comment]
It looks like Auth Client is also happy to translate 401s from Auth Service to 500s 😬

**Comment by halkyon** [comment]
> It looks like Auth Client is also happy to translate 401s from Auth Service to 500s grimacing

True. I've seen Linksharing respond with a 500 with a key wasn't there :grimacing:
