### ISSUE TITLE
Figure out how much of the test plan for Custom Domains over TLS is already automated

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#306]
### Goal

We want to automate the test plan or parts of it for Custom Domains over TLS. Tests we have written down in this repository might partially cover what needs to be done.

### Acceptance Criteria

- Green-color parts of the test plan that we already cover with tests in this repository
- Create issues for what's left

### Links

- https://github.com/storj/storj/issues/5125

**Comment by pwilloughby** [comment]
https://github.com/letsencrypt/pebble looks like it could be useful for covering a lot of the tests.

**Comment by amwolff** [comment]
Here are all the test cases from the test plan:

- General/Pro Account Only
- General/HTTPS Support
- General/Host TLS certificates
- General/Certificate Generation
- General/Custom Domain URL
- General/BYO Certificate (out of scope)
- General/uplink CLI share request
- General/Share Access 1
- General/Share Access 2
- General/Valid/Invalid Handshake
- General/Successful domain-lock
- General/Multiple Request on domain-lock
- Migration Impact/Valid Certificate Return
- Migration Impact/Warning For HTTPS Support
- Migration Impact/Opt-in TLS Custom Domains
- Certificates/Storing
- Certificates/On-access Renewal
- Certificates/Expired Certificate

TCs that were already automated:

- General/Host TLS certificates
- General/Multiple Request on domain-lock
- Certificates/Storing

TCs that will be covered with a single test that constitutes of using Custom Domains over TLS once in a scenario where everything's supposed to work:

- General/HTTPS Support
- General/Host TLS certificates
- General/Certificate Generation
- General/Custom Domain URL
- General/Share Access 1
- General/Successful domain-lock
- Migration Impact/Valid Certificate Return
- Migration Impact/Warning For HTTPS Support
- Migration Impact/Opt-in TLS Custom Domains
- Certificates/Storing

Remaining TCs:

- General/Pro Account Only
- General/uplink CLI share request
- General/Share Access 2
- General/Valid/Invalid Handshake
- Certificates/On-access Renewal
- Certificates/Expired Certificate

**Comment by amwolff** [comment]
> Create issues for what's left

- #313
- storj/storj#5623
- #314
- #315
