### ISSUE TITLE
Determine Current Capacity

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#308]
### Goal

- The goal is to determine what our current capacity is (+- 20%, doesn’t need to be super precise)
-  Start with just TR2 to keep things simple ([Link to edge deployment details](https://storjlabs.atlassian.net/wiki/spaces/OPS/pages/1667858433/Edge+Service+Deployment+Details#TR2))
  - This will act as a baseline to compare new providers against
  - Doesn’t need to be precise - we’d like to get this estimate soon
  - Components would include compute, storage, egress, firewalls, etc

### Acceptance Criteria

- TR2 capacity for edge services documented
- Components:
  - Storage
    - Does this have multiple components? Auth service? Certificate buckets? Anything else?
  - Egress
  - App Server CPU
  - App Server RAM
  - Firewall Server CPU ?
  - Firewall Server RAM ? 
  - Other components ? 
 - Provide an estimate for how much throughput the described setup allows for common usage patterns:
   - 100% Uploads (backup)
   - 100% Downloads (video streaming/content delivery)
   - 50/50 Up/Down
   - What is our average up/down -- include that as well

### For grooming
- Determine what the components of capacity are and add to acceptance criteria

### Links

 - TBD: Link to documentation

**Comment by stefanbenten** [comment]
Does this factor in current state snapshot? Or after the work to rework the routing within the DCs? :)

**Comment by ferristocrat** [comment]
> Does this factor in current state snapshot? Or after the work to rework the routing within the DCs? :)

Was initially thinking current state, but would be dumb not to factor in work in progress that will improve things... we can chat more about it this week and refine to something that makes more sense
