### ISSUE TITLE
The `--domain-name` parameter collides with CertMagic's configuration and MinIO

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#311]
## Current Behavior

When I provide `--domain-name=gateway.qa.storjshare.io,*.gateway.storjshare.io` so that CertMagic can request certificates for both domains, underlying MinIO complains that it cannot ingest duplicate domains.

## Possible Solution

There's a part in gateway-mt's code where we wire up the API router:

https://github.com/storj/gateway-mt/blob/984a779acb2309ac7740fa76ee9cd31f5b0be4ae/pkg/server/server.go#L80

This is where we shouldn't be passing duplicate domains even though we need them so that CertMagic can request certificates for them.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Implementation

Just an idea: make a function that takes domains, strips `*.` if needed (MinIO won't like this), and deduplicates using `map[string]struct{}`.

**Comment by halkyon** [comment]
> This is where we shouldn't be passing duplicate domains even though we need them so that CertMagic can request certificates for them.

The error comes from the `MINIO_DOMAIN` environment set in the command code: `Invalid MINIO_DOMAIN value in environment variable: Overlapping domains `[*.gateway.local gateway.local]` not allowed`. I couldn't catch this in a test until I set the env var directly. Agree we should deduplicate and set the router domains to the filtered list as well, though.

The way we're doing things is a bit weird currently. The command code sets `MINIO_DOMAIN` to the unparsed comma separated domain list, then we do our own parsing in server.New() and set up the routes in RegisterAPIRouter with those. I'm thinking we should shift the env setting into the peer so both MINIO_DOMAIN and the routes use the same filtered domain list. It feels kind of weird to be setting an environment variable in the peer, but then again minio is still very much used as global so it probably wouldn't hurt, and we'll catch any problems in a peer test.
