### ISSUE TITLE
Make libuplink's MaximumStep configurable

### ISSUE THREAD

**Issue by amwolff** [storj/gateway-mt#317]
### Goal

We need to surface [the `MaximumStep` parameter](https://github.com/storj/uplink/blob/b981b70bc7952ca86d02c95cec793d58a7ef081c/private/piecestore/client.go#L53) to make it configurable for the gateway. The default value can cause high consumption of resources when there are many parallel uploads to the gateway.

### Acceptance Criteria

MaximumStep can be configured by passing the size value to the gateway's config for this parameter.

### Links

Here's the object that I believe needs to be modified from the gateway for this to work:

https://github.com/storj/uplink/blob/b981b70bc7952ca86d02c95cec793d58a7ef081c/private/piecestore/client.go#L48-L56

**Comment by jtolio** [comment]
So, actually, I'm not really sure this is something we want to expose. I agree we should reduce memory usage, but exposing this internal detail might not be as good as just fixing the memory usage.

For context, the reason we have InitialStep and MaximumStep is as follows:

 * The uplink is talking to a storage node it has potentially never trusted before. The uplink is going to be sending a signed order limit (essentially a cashier's check, like at the bank) for bandwidth usage. 
 * The storage node could take that cashier's check and just go cash it, not returning any data but still getting paid.
 * This is a core aspect of our protocol - to keep things fast, the Uplink takes this risk right off the bat.
 * To make sure that the uplink's risk isn't too great, it does not send a signed order for the full request, just this small amount. 
 * As the storage node continues to return data successfully, the Uplink has greater and greater reason to trust this storage node, and so sends larger and larger signed orders for subsequent data.
 
The above design is important and probably not something the gateway codebase should be making decisions about. This is something that should be an uplink strategy internal detail.

Notice that nothing about the design above has requirements on how much memory is used for buffering! The fact that these values are also controlling buffering in memory is what we need to fix, not changing the values.

**Comment by jtolio** [comment]
Also worth noting that this change may also be contributing: https://github.com/storj/common/commit/81c8060f089b83dc88a8f7ff39a32d98a7786f38

The reason that change happened is because we want the largest possible write per noise message to reduce handshake roundtrips, so I definitely care about the InitialStep in the above ticket being 64K or so.

**Comment by amwolff** [comment]
I think your points make sense if you're worried about configuring the gateway in a way that it would send signed orders for parts of the request much larger than the default or even the full requests, but I want to do the opposite.

Overall, I agree with your points, but I'm looking for the easiest ways to reduce memory consumption right now (I'll reach out internally to talk about this).

**Comment by jtolio** [comment]
https://review.dev.storj.io/c/storj/uplink/+/9814

**Comment by amwolff** [comment]
okay, we bumped dependencies to include 9814, and that should do what this issue was talking about, but in a better way, so I'm closing this as not planned.
