### ISSUE TITLE
Add new domains for the exclusive use of the satellite UI

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#320]
### Summary
If the storjshare domain is blocked, then the satellite file browser will not work for customers. This is becoming a bigger issue as our public storjshare domain continues to get flagged for hosting harmful/malicious content.

### Acceptance

Any user-generated content accessed via the Satellite UI should be on a separate domain from the satellite 

- Add a new link sharing domain for the exclusive use of the Satellite UI
- Add a new Gateway-MT domain for the exclusive use of the Satellite UI
  - Add a new authservice domain for the exclusive use of the Satellite UI
- User generated linkshares (either through Satellite UI or elsewhere will continue to use the storjshare.io domain)
- Create issues to make appropriate changes in Console/UI so that appropriate domains are used/returned

### Notes
Proposals for domains:
- [storjsatelliteshare.io](http://storjsatelliteshare.io/)
- [satelliteshare.io](http://satelliteshare.io/)
- [storjshare.website](http://storjshare.website)

**Comment by stefanbenten** [comment]
I also own storj.network which i can offer for use.

**Comment by pwilloughby** [comment]
I think the idea is to have the satellite UI talk to edge on it's own domains that are never used for user generated content so they won't be blocked and the satellite UI always works.

**Comment by halkyon** [comment]
Should we add this acceptance criteria as well? Maybe it's implied by Gateway-MT, but it's probably still worth adding?

"- Add a new authservice domain for the exclusive use of the Satellite UI"
