### ISSUE TITLE
Inconsistent performance from production gateway-mt instances

### ISSUE THREAD

**Issue by elek** [storj/gateway-mt#324]
I noticed that deployed gateway-mt serves the request quite slowly time-to-time.

For example, from the last 24 hours:

![image](https://user-images.githubusercontent.com/170549/229471999-978275fe-445f-4ed0-88dd-fc7b23803359.png)

This makes to achieve our performance goals very hard.

## Links

- https://storj.slack.com/archives/C0196DNUML0/p1678882980365059

**Comment by elek** [comment]
More comments: 
![image](https://user-images.githubusercontent.com/170549/229472160-226f36df-45b0-42c2-afdf-d788a4e2a57b.png)

**Comment by elek** [comment]
What is a request ID? ;-) 

If it's something which is connected to distributed tracing, I should have it. If it's only for request/response, I don't have it I think.

How would you use it?

**Comment by ferristocrat** [comment]
Needs Grooming: update with acceptance criteria @amwolff

**Comment by amwolff** [comment]
I'm honestly not sure what the acceptance criteria should be here. I believe this issue should just encompass investigating possible explanations for why we have these weird latency spikes and creating issues to fix problems that came out of the investigation.

**Comment by elek** [comment]
> I'm honestly not sure what the acceptance criteria should be here. I believe this issue should just encompass investigating possible explanations for why we have these weird latency spikes and creating issues to fix problems that came out of the investigation.

I think we narrowed down the root causes recently. All the spikes from the additional Hetzner boxes.

However we don't really know the reason of slowness.

But if the Hetzner boxes can be replaced in very near future, it may fix this problem.
