### ISSUE TITLE
Evaluate ways of identifying malicious content

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#344]
### Goal

The goal of this task is to come up with a plan after conducting research and evaluation on how to improve the identification of malicious content in Link Sharing Service. The objective is to enhance the system's ability to detect unsafe content before it is reported while also prioritizing user privacy.

### What needs to be done + Acceptance Criteria

1. Develop a plan for implementing a method to identify and handle malicious content served through Link Sharing Service
2. Consider a simple approach, such as calculating file digests on download using a hash database of known malicious files
3. Evaluate the feasibility of integrating ClamAV into the system and assess its resource impact
4. Explore other potential ideas or techniques to enhance the detection of unsafe content
5. Document the findings from the research and evaluation process

### Links

- [ClamAV Documentation](https://docs.clamav.net/)
- [Automate Malware Scanning for Documents Uploaded to Cloud Storage](https://cloud.google.com/architecture/automate-malware-scanning-for-documents-uploaded-to-cloud-storage)

**Comment by VitaliiShpital** [comment]
I'm not sure if it's usefull nor I assigned this to myself but I discussed this topic with Chat-GPT. Here are 2 points which were provided

- Implement Automated Scanning: You can integrate an automated scanning system into your platform. This system would scan uploaded files using antivirus software or specialized tools for detecting malware, viruses, or other types of malicious content. There are several third-party services and software available that provide API-based file scanning capabilities.

- Utilize File Reputation Services: Some companies offer file reputation services that provide information about the reputation and safety of a file based on its hash or metadata. These services maintain databases of known malicious files and can help flag potentially harmful content.

So chat-gpt provided some example of the tool called VirusTotal

```
To utilize a file reputation service like VirusTotal in your Golang implementation, you can make use of their public API. Here's an example code snippet that demonstrates how to send a file to VirusTotal for analysis and retrieve the reputation results:
```

```
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"mime/multipart"
	"net/http"
	"os"
)

const VirusTotalAPIURL = "https://www.virustotal.com/api/v3/files"

func main() {
	filePath := "path/to/your/file.txt"

	// Read the file data
	file, err := os.Open(filePath)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	// Create a new HTTP request with the file
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)
	part, err := writer.CreateFormFile("file", filePath)
	if err != nil {
		log.Fatal(err)
	}
	_, err = io.Copy(part, file)
	if err != nil {
		log.Fatal(err)
	}
	writer.Close()

	// Create the HTTP request to send to VirusTotal
	req, err := http.NewRequest("POST", VirusTotalAPIURL, body)
	if err != nil {
		log.Fatal(err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())
	req.Header.Set("x-apikey", "YOUR_VIRUSTOTAL_API_KEY") // Replace with your VirusTotal API key

	// Send the request
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	// Read the response
	respBody, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}

	// Parse the JSON response
	var result map[string]interface{}
	err = json.Unmarshal(respBody, &result)
	if err != nil {
		log.Fatal(err)
	}

	// Access the reputation information
	data := result["data"].(map[string]interface{})
	attributes := data["attributes"].(map[string]interface{})
	reputation := attributes["last_analysis_stats"].(map[string]interface{})["malicious"].(float64)

	fmt.Printf("Malicious: %.0f%%\n", reputation*100)
}
```

```
In this example, you need to replace "YOUR_VIRUSTOTAL_API_KEY" with your actual VirusTotal API key. The code sends a POST request to the VirusTotal API with the file as a form data parameter. It then reads the response, parses the JSON, and extracts the reputation information. Finally, it prints the maliciousness percentage.

Please note that you'll need to sign up for a VirusTotal API key and ensure you comply with their usage policies and any rate limits they have in place.
```

Their API also provides some interesting features that could be found here
https://developers.virustotal.com/reference/overview

Besides that I asked if there is an option to use ClamAV

The answer:

```
To implement ClamAV in your Golang application, you can use the "github.com/dutchcoders/go-clamd" package, which provides a client library for interacting with ClamAV's clamd daemon. Here's an example code snippet that demonstrates how to use go-clamd to scan a file using ClamAV:
```

```
package main

import (
	"fmt"
	"log"

	clamd "github.com/dutchcoders/go-clamd"
)

func main() {
	// Create a new ClamAV client
	clamav, err := clamd.NewClamd("localhost:3310") // Replace with your ClamAV server address
	if err != nil {
		log.Fatal(err)
	}

	// Scan a file
	filePath := "path/to/your/file.txt"
	response, err := clamav.ScanFile(filePath)
	if err != nil {
		log.Fatal(err)
	}

	// Check the scan result
	if response.Status == "OK" {
		fmt.Println("File is clean")
	} else {
		fmt.Println("File is infected")
		fmt.Println("Virus name:", response.VirusName)
		fmt.Println("Description:", response.Description)
	}
}
```

```
In this example, you need to replace "localhost:3310" with the address of your ClamAV server. The code creates a new ClamAV client and then uses the ScanFile function to scan the specified file. The response from the scan includes the status, virus name (if infected), and description.

Make sure you have ClamAV installed and running on your server before using this code. Additionally, ensure that the ClamAV server is configured to allow connections from your Golang application.
```

**Comment by amwolff** [comment]
Paul's draft on this issue (internal): https://docs.google.com/document/d/1SZktbSJitS4NjppDb4xte9fjNu55f8DKKbQAriBxb5M/edit?usp=sharing
