### ISSUE TITLE
Review MinIO's test suite (mint) to find potential improvements to requirements for Object Versioning

### ISSUE THREAD

**Issue by ferristocrat** [storj/gateway-mt#351]
## Motivation/Why?

Our integration test suites are quite good at finding edge cases in certain features of S3. We should review them to find any potential edge cases that PRD doesn't list as requirements.

## What needs to be done?

Review object versioning tests from MinIO's test suite (mint) to find any potential edge cases. Verify them against the Requirements section of [this document](https://docs.google.com/document/d/1gZH5IWntGX-dcSsMSsgEeDGGQS-6emrppnksy9zZbkM/edit?usp=sharing).

## Acceptance Criteria

Additional edge cases are reported in the document as suggestions or comments, and product managers are aware of changes that need to be made to the requirements documents.

**Paul proposes to review [JT's change to implement versioning in our MinIO fork](https://review.dev.storj.io/c/storj/gateway/+/10925)** (see https://github.com/storj/gateway-mt/issues/351#issuecomment-1679485153).

## Links

- https://github.com/storj/roadmap/issues/23
- https://github.com/storj/mint
- https://github.com/minio/mint

**Comment by ferristocrat** [comment]
Make sure to cover the following S3 endpoints:

- [PutBucketVersioning](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketVersioning.html): Sets the versioning state of an existing bucket.
- [GetBucketVersioning](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketVersioning.html): Returns the versioning state of a bucket.
- [ListObjectVersions](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html): Returns metadata about all versions of the objects in a bucket.
- [GetObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html): Retrieves objects from Amazon S3. You can specify a version ID to retrieve a specific version of the object.
- [PutObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html): Adds an object to a bucket. If versioning is enabled, a new version of the object is created.
- [DeleteObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html): Removes the null version (if there is one) of an object and inserts a delete marker, which becomes the latest version of the object. If versioning is not enabled, it permanently deletes the object.

**Comment by amwolff** [comment]
JT says that MinIO's mint test suite is very basic and doesn't test the whole breadth of the versioning feature of the S3 protocol.

JT's change to implement versioning in our MinIO fork: https://review.dev.storj.io/c/storj/gateway/+/10925

Paul's proposal is to review JT's change as part of this issue.
