### ISSUE TITLE
Flag for disabling http/2

### ISSUE THREAD

**Issue by NiaStorj** [storj/gateway-mt#430]
#### Context
We have observed that the performance of backups using Veeam on Storj seems to degrade, which might be linked to the HTTP/2 protocol's handling of our data transfer.

#### Expected Outcome from Disabling HTTP/2
1. Enhanced Transfer Speed: Without the multiple stream capabilities of HTTP/2, we expect to avoid prioritization and resource allocation issues leading to higher throughput
2. Ruling out HTTP/2: If there are no noticable changes, we can at least rule out our gateway's use of HTTP/2 as a contributing factor

### Acceptance Criteria
- Disable HTTP/2 on the gateway
- @derek-storj to run benchmarks against gateway with HTTP/2 disabled

**Comment by derek-storj** [comment]
Placing a proxy in front of Veeam has proven to be a bottleneck, so did some testing with rclone with a workload that mimics Veeam behavior:

Created a folder with 20GB worth of 4MB files, then used rclone to copy that folder to Storj.

64 concurrent transfers, HTTP2 enabled -> 2:37 (131MB/s)
64 concurrent transfers, HTTP2 disabled -> 0:57 (380MB/s), ~3x improvement

(Running netstat from Windows CLI confirms HTTP2 disabled shows 64 connections opened to 136.0.77.2, versus HTTP2 enabled shows 1 connection)

**Comment by derek-storj** [comment]
https://storj.slack.com/archives/C06BDR8SC5Q/p1715186028011289
