### ISSUE TITLE
Auth service DB blueprint

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#50]
We want to provide an alternative to using CockroachDB.  We have another ticket for creating a TiKV provider for test purposes.  What if we wrote something from scratch?  Create a blueprint.

How can we test this at scale?  What do we need for migrations?

**Comment by amwolff** [comment]
Current work on the new auth database blueprint is tracked here: https://review.dev.storj.io/c/storj/gateway-mt/+/6030.
