### ISSUE TITLE
Fix release versioning

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#58]
The edge services can't report their version number correctly, because the versioning build process doesn't quite work right for them.  We end up having to manually set flags which say its a release build, etc.  Also, since we create that process, Go now supports release tagging as a feature, without our custom process.  Find what make sense for Edge and update things so our releases are properly tagged.

**Comment by halkyon** [comment]
The immediate issue with `storj-release` not setting the ldflags is fixed here: https://review.dev.storj.io/c/storj/ci/+/6193, but there's more work to be done on how we could do this better.

**Comment by amwolff** [comment]
Closed by https://github.com/storj/ci/commit/67bd7613178786cb1fe2787e602e616ea7070f18.
