### ISSUE TITLE
Re-add credential caching to Gateway-MT

### ISSUE THREAD

**Issue by halkyon** [storj/gateway-mt#69]
As part of recent refactoring of authentication in Gateway-MT, we're no longer caching credentials as was previously being done by minio. This means every S3 request is going to the authservice.

We'll want to introduce a cache again of some form, possibly re-using what Linksharing is doing for this.

**Comment by amwolff** [comment]
This needs verification.

**Comment by halkyon** [comment]
I can't replicate this anymore, so we must've added the credential caching back. I run multiple requests to gateway for the same credentials and authservice only had one request for them.
