### ISSUE TITLE
Edge services: Cache valid but non-existing access key IDs

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#85]
We want to cache the access key IDs (which can be parsed successfully) that don't resolve in an existing access grant (i.e. the authservice returns status 404).

JT Olio expressed this idea in this slack thread https://storj.slack.com/archives/CAQV0AE2Z/p1625249529154900

**Comment by ifraixedes** [comment]
Is there any delay since an access key ID is registered and available in the Auth Service?

On the other hand, with the rate-limiting in place, the client IP will be banned for a certain period of time, making a potential bad actor not being able to overload our DB.

**Comment by amwolff** [comment]
Ivan's rate-limiting changes closes this.
