### ISSUE TITLE
Investigate "modification time" failures

### ISSUE THREAD

**Issue by wthorp** [storj/gateway-mt#94]
This issue is likely already fixed, but has not been confirmed:

https://storjlabs.atlassian.net/browse/USR-1750

gateway.eu1.storjshare.io with rclone: Failed to set modification time: NotImplemented: A header you provided implies functionality that is not implemented

The ticket says this works on Gateway-ST so I imagine there's a metadata endpoints that was removed and subsequently restored. https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html

**Comment by halkyon** [comment]
It's hard to know exactly what could be causing that not implemented error, but I'm not able to replicate it with rclone or setting metadata directly, and it looks like an old ticket, so I guess we can close it.

**Comment by wthorp** [comment]
Hmmm, we added this because it seemed to correspond to https://github.com/storj/gateway-st/issues/44, so it seems to still be actively reported.  We might want to get a second look at this.

**Comment by halkyon** [comment]
oops, didn't see that one. I'll check it out!

**Comment by amwolff** [comment]
Closed by #44.
